"""initial schema

Revision ID: eff487ab9235
Revises: a1e7c0
Create Date: 2026-08-07 08:44:10.661798
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'eff487ab9235'
down_revision: str | None = 'a1e7c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Every table carrying updated_at gets the trigger from revision a1e7c0.
# ORM-level onupdate does not fire for bulk UPDATEs or raw SQL; the trigger does.
TIMESTAMPED_TABLES = (
    "agent_executions",
    "campaigns",
    "chat_messages",
    "company_profiles",
    "contacts",
    "conversations",
    "email_drafts",
    "knowledge_chunks",
    "knowledge_sources",
    "leads",
    "prospect_companies",
    "research",
    "sent_emails",
    "timeline_events",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'prospecting', 'researching', 'ready', 'running', 'paused', 'completed', name='campaign_status', native_enum=False, create_constraint=True), server_default='draft', nullable=False),
    sa.Column('target_criteria', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_workspace_id'), 'campaigns', ['workspace_id'], unique=False)
    op.create_table('company_profiles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icp_description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('onboarding', 'analyzing', 'ready', name='company_profile_status', native_enum=False, create_constraint=True), server_default='onboarding', nullable=False),
    sa.Column('product_knowledge', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('knowledge_ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_profiles'))
    )
    op.create_index(op.f('ix_company_profiles_workspace_id'), 'company_profiles', ['workspace_id'], unique=False)
    op.create_table('conversations',
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.create_index('ix_conversations_workspace_last', 'conversations', ['workspace_id', 'last_message_at'], unique=False)
    op.create_table('prospect_companies',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('employee_range', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('enrichment', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('last_researched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prospect_companies')),
    sa.UniqueConstraint('workspace_id', 'domain', name='workspace_domain')
    )
    op.create_index('ix_prospect_companies_industry', 'prospect_companies', ['workspace_id', 'industry'], unique=False)
    op.create_index(op.f('ix_prospect_companies_workspace_id'), 'prospect_companies', ['workspace_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='chat_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('agent_outputs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_chat_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_messages_conversation_created', 'chat_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_workspace_id'), 'chat_messages', ['workspace_id'], unique=False)
    op.create_table('contacts',
    sa.Column('prospect_company_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('role_category', sa.Enum('founder', 'ceo', 'marketing', 'growth', 'sales', 'operations', 'engineering', 'other', name='contact_role', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_status', sa.Enum('verified', 'guessed', 'unknown', 'not_found', name='email_status', native_enum=False, create_constraint=True), server_default='unknown', nullable=False),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_contacts_confidence_between_zero_and_one')),
    sa.ForeignKeyConstraint(['prospect_company_id'], ['prospect_companies.id'], name=op.f('fk_contacts_prospect_company_id_prospect_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index('ix_contacts_company_role', 'contacts', ['prospect_company_id', 'role_category'], unique=False)
    op.create_index(op.f('ix_contacts_workspace_id'), 'contacts', ['workspace_id'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('company_profile_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('brochure', 'pitch_deck', 'case_study', 'documentation', 'website', 'other', name='knowledge_source_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'parsing', 'ready', 'failed', name='knowledge_source_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_knowledge_sources_size_bytes_non_negative')),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], name=op.f('fk_knowledge_sources_company_profile_id_company_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_sources'))
    )
    op.create_index('ix_knowledge_sources_company_status', 'knowledge_sources', ['company_profile_id', 'status'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_workspace_id'), 'knowledge_sources', ['workspace_id'], unique=False)
    op.create_table('leads',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('prospect_company_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('discovered', 'researching', 'qualified', 'rejected', 'outreach_ready', 'approved', 'sent', name='lead_status', native_enum=False, create_constraint=True), server_default='discovered', nullable=False),
    sa.Column('fit_score', sa.SmallInteger(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('qualification_reason', sa.Text(), nullable=True),
    sa.Column('qualification_evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('opportunity_summary', sa.Text(), nullable=True),
    sa.Column('opportunity_evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_leads_confidence_between_zero_and_one')),
    sa.CheckConstraint('fit_score IS NULL OR (fit_score >= 0 AND fit_score <= 100)', name=op.f('ck_leads_fit_score_between_zero_and_hundred')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_leads_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prospect_company_id'], ['prospect_companies.id'], name=op.f('fk_leads_prospect_company_id_prospect_companies'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('campaign_id', 'prospect_company_id', name='campaign_prospect')
    )
    op.create_index('ix_leads_campaign_score', 'leads', ['campaign_id', 'fit_score'], unique=False)
    op.create_index(op.f('ix_leads_workspace_id'), 'leads', ['workspace_id'], unique=False)
    op.create_index('ix_leads_workspace_status', 'leads', ['workspace_id', 'status'], unique=False)
    op.create_table('research',
    sa.Column('prospect_company_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('langfuse_trace_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prospect_company_id'], ['prospect_companies.id'], name=op.f('fk_research_prospect_company_id_prospect_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research'))
    )
    op.create_index('ix_research_company_created', 'research', ['prospect_company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_research_workspace_id'), 'research', ['workspace_id'], unique=False)
    op.create_table('agent_executions',
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', name='execution_status', native_enum=False, create_constraint=True), server_default='running', nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('langfuse_trace_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_agent_executions_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_agent_executions_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_agent_executions_lead_id_leads'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_executions'))
    )
    op.create_index('ix_agent_executions_agent_created', 'agent_executions', ['agent_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_executions_workspace_id'), 'agent_executions', ['workspace_id'], unique=False)
    op.create_index('ix_agent_executions_workspace_status', 'agent_executions', ['workspace_id', 'status'], unique=False)
    op.create_table('email_drafts',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('linkedin_message', sa.Text(), nullable=True),
    sa.Column('follow_up', sa.Text(), nullable=True),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'edited', 'skipped', name='draft_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('edited_by_human', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('critic_verdict', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_email_drafts_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_email_drafts_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_drafts'))
    )
    op.create_index('ix_email_drafts_lead_revision', 'email_drafts', ['lead_id', 'revision'], unique=False)
    op.create_index(op.f('ix_email_drafts_workspace_id'), 'email_drafts', ['workspace_id'], unique=False)
    op.create_index('ix_email_drafts_workspace_status', 'email_drafts', ['workspace_id', 'status'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('knowledge_source_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_sources.id'], name=op.f('fk_knowledge_chunks_knowledge_source_id_knowledge_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_chunks'))
    )
    op.create_index('ix_knowledge_chunks_embedding', 'knowledge_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_knowledge_chunks_source_index', 'knowledge_chunks', ['knowledge_source_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_workspace_id'), 'knowledge_chunks', ['workspace_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('prospect_company_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('discovered', 'researched', 'qualified', 'rejected', 'contact_found', 'draft_generated', 'draft_approved', 'draft_rejected', 'email_sent', 'email_replied', name='timeline_event_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_timeline_events_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_timeline_events_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prospect_company_id'], ['prospect_companies.id'], name=op.f('fk_timeline_events_prospect_company_id_prospect_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events'))
    )
    op.create_index('ix_timeline_events_campaign_created', 'timeline_events', ['campaign_id', 'created_at'], unique=False)
    op.create_index('ix_timeline_events_lead_created', 'timeline_events', ['lead_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_timeline_events_workspace_id'), 'timeline_events', ['workspace_id'], unique=False)
    op.create_table('sent_emails',
    sa.Column('email_draft_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('smtp', 'resend', name='email_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('provider_message_id', sa.String(length=512), nullable=True),
    sa.Column('to_email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bounced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_draft_id'], ['email_drafts.id'], name=op.f('fk_sent_emails_email_draft_id_email_drafts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sent_emails'))
    )
    op.create_index('ix_sent_emails_provider_message', 'sent_emails', ['provider', 'provider_message_id'], unique=True, postgresql_where=sa.text('provider_message_id IS NOT NULL'))
    op.create_index(op.f('ix_sent_emails_workspace_id'), 'sent_emails', ['workspace_id'], unique=False)
    # ### end Alembic commands ###

    for table in TIMESTAMPED_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_updated_at "
            f"BEFORE UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )


def downgrade() -> None:
    for table in TIMESTAMPED_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_updated_at ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sent_emails_workspace_id'), table_name='sent_emails')
    op.drop_index('ix_sent_emails_provider_message', table_name='sent_emails', postgresql_where=sa.text('provider_message_id IS NOT NULL'))
    op.drop_table('sent_emails')
    op.drop_index(op.f('ix_timeline_events_workspace_id'), table_name='timeline_events')
    op.drop_index('ix_timeline_events_lead_created', table_name='timeline_events')
    op.drop_index('ix_timeline_events_campaign_created', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_knowledge_chunks_workspace_id'), table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_source_index', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_embedding', table_name='knowledge_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('knowledge_chunks')
    op.drop_index('ix_email_drafts_workspace_status', table_name='email_drafts')
    op.drop_index(op.f('ix_email_drafts_workspace_id'), table_name='email_drafts')
    op.drop_index('ix_email_drafts_lead_revision', table_name='email_drafts')
    op.drop_table('email_drafts')
    op.drop_index('ix_agent_executions_workspace_status', table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_workspace_id'), table_name='agent_executions')
    op.drop_index('ix_agent_executions_agent_created', table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index(op.f('ix_research_workspace_id'), table_name='research')
    op.drop_index('ix_research_company_created', table_name='research')
    op.drop_table('research')
    op.drop_index('ix_leads_workspace_status', table_name='leads')
    op.drop_index(op.f('ix_leads_workspace_id'), table_name='leads')
    op.drop_index('ix_leads_campaign_score', table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_knowledge_sources_workspace_id'), table_name='knowledge_sources')
    op.drop_index('ix_knowledge_sources_company_status', table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index(op.f('ix_contacts_workspace_id'), table_name='contacts')
    op.drop_index('ix_contacts_company_role', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_chat_messages_workspace_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_conversation_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_prospect_companies_workspace_id'), table_name='prospect_companies')
    op.drop_index('ix_prospect_companies_industry', table_name='prospect_companies')
    op.drop_table('prospect_companies')
    op.drop_index('ix_conversations_workspace_last', table_name='conversations')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_company_profiles_workspace_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    op.drop_index(op.f('ix_campaigns_workspace_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
