"""email threads and messages

Revision ID: 7514d9ecfcd5
Revises: eff487ab9235
Create Date: 2026-08-08 08:01:46.035306
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7514d9ecfcd5"
down_revision: str | None = "eff487ab9235"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

NEW_TIMESTAMPED_TABLES = ("email_threads", "email_messages")

# Bare name: the metadata naming convention renders it as
# ck_%(table_name)s_%(constraint_name)s, so passing the full name prefixes twice.
TIMELINE_KIND_CONSTRAINT = "timeline_event_kind"

TIMELINE_KINDS_OLD = (
    "discovered",
    "researched",
    "qualified",
    "rejected",
    "contact_found",
    "draft_generated",
    "draft_approved",
    "draft_rejected",
    "email_sent",
    "email_replied",
)

# The reply loop needs its own events: opens and bounces feed the Learning
# Agent, high_intent/handed_off drive the hand-off to a human, and
# deal_won/deal_lost are what any of it is ultimately scored against.
TIMELINE_KINDS_NEW = (
    *TIMELINE_KINDS_OLD,
    "email_opened",
    "email_bounced",
    "high_intent",
    "handed_off",
    "deal_won",
    "deal_lost",
)


def _kind_in(values: tuple[str, ...]) -> str:
    joined = ", ".join(f"'{value}'" for value in values)
    return f"kind IN ({joined})"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_threads",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column(
            "provider",
            sa.Enum(
                "smtp",
                "resend",
                "gmail",
                "outlook",
                name="email_provider",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("provider_thread_id", sa.String(length=512), nullable=True),
        sa.Column("subject", sa.String(length=512), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "awaiting_reply",
                "replied",
                "high_intent",
                "handed_off",
                "not_interested",
                "bounced",
                "closed_won",
                "closed_lost",
                name="thread_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="awaiting_reply",
            nullable=False,
        ),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("high_intent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("human_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("handed_off_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_email_threads_contact_id_contacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_email_threads_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_threads")),
    )
    op.create_index(
        "ix_email_threads_last_activity",
        "email_threads",
        ["workspace_id", "last_activity_at"],
        unique=False,
    )
    op.create_index(
        "ix_email_threads_provider_thread",
        "email_threads",
        ["provider", "provider_thread_id"],
        unique=True,
        postgresql_where=sa.text("provider_thread_id IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_email_threads_workspace_id"), "email_threads", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_email_threads_workspace_status",
        "email_threads",
        ["workspace_id", "status"],
        unique=False,
    )
    op.create_table(
        "email_messages",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("email_draft_id", sa.UUID(), nullable=True),
        sa.Column(
            "direction",
            sa.Enum(
                "outbound",
                "inbound",
                name="message_direction",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.Enum(
                "smtp",
                "resend",
                "gmail",
                "outlook",
                name="email_provider",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("provider_message_id", sa.String(length=512), nullable=True),
        sa.Column("in_reply_to", sa.String(length=512), nullable=True),
        sa.Column("from_email", sa.String(length=320), nullable=True),
        sa.Column("to_email", sa.String(length=320), nullable=True),
        sa.Column("subject", sa.String(length=512), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bounced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "classification",
            sa.Enum(
                "interested",
                "pricing",
                "meeting_request",
                "follow_up",
                "not_interested",
                "auto_reply",
                "unknown",
                name="reply_classification",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "analysis",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["email_draft_id"],
            ["email_drafts.id"],
            name=op.f("fk_email_messages_email_draft_id_email_drafts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["email_threads.id"],
            name=op.f("fk_email_messages_thread_id_email_threads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_messages")),
    )
    op.create_index(
        "ix_email_messages_provider_message",
        "email_messages",
        ["provider", "provider_message_id"],
        unique=True,
        postgresql_where=sa.text("provider_message_id IS NOT NULL"),
    )
    op.create_index(
        "ix_email_messages_thread_created",
        "email_messages",
        ["thread_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_email_messages_workspace_direction",
        "email_messages",
        ["workspace_id", "direction"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_messages_workspace_id"), "email_messages", ["workspace_id"], unique=False
    )
    op.drop_index(
        op.f("ix_sent_emails_provider_message"),
        table_name="sent_emails",
        postgresql_where="(provider_message_id IS NOT NULL)",
    )
    op.drop_index(op.f("ix_sent_emails_workspace_id"), table_name="sent_emails")
    op.drop_table("sent_emails")
    # ### end Alembic commands ###

    for table in NEW_TIMESTAMPED_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_updated_at BEFORE UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )

    # Autogenerate cannot see enum CHECK constraints (see include_object in
    # migrations/env.py), so new enum values are written by hand.
    op.drop_constraint(TIMELINE_KIND_CONSTRAINT, "timeline_events", type_="check")
    op.create_check_constraint(
        TIMELINE_KIND_CONSTRAINT, "timeline_events", _kind_in(TIMELINE_KINDS_NEW)
    )


def downgrade() -> None:
    op.drop_constraint(TIMELINE_KIND_CONSTRAINT, "timeline_events", type_="check")
    op.create_check_constraint(
        TIMELINE_KIND_CONSTRAINT, "timeline_events", _kind_in(TIMELINE_KINDS_OLD)
    )

    for table in NEW_TIMESTAMPED_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_updated_at ON {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sent_emails",
        sa.Column("email_draft_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("provider", sa.VARCHAR(length=6), autoincrement=False, nullable=False),
        sa.Column(
            "provider_message_id", sa.VARCHAR(length=512), autoincrement=False, nullable=True
        ),
        sa.Column("to_email", sa.VARCHAR(length=320), autoincrement=False, nullable=False),
        sa.Column("subject", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
        sa.Column("body", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "sent_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "opened_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "replied_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column(
            "bounced_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.Column("error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("workspace_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider::text = ANY (ARRAY['smtp'::character varying, 'resend'::character varying]::text[])",
            name=op.f("ck_sent_emails_email_provider"),
        ),
        sa.ForeignKeyConstraint(
            ["email_draft_id"],
            ["email_drafts.id"],
            name=op.f("fk_sent_emails_email_draft_id_email_drafts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sent_emails")),
    )
    op.create_index(
        op.f("ix_sent_emails_workspace_id"), "sent_emails", ["workspace_id"], unique=False
    )
    op.create_index(
        op.f("ix_sent_emails_provider_message"),
        "sent_emails",
        ["provider", "provider_message_id"],
        unique=True,
        postgresql_where="(provider_message_id IS NOT NULL)",
    )
    op.drop_index(op.f("ix_email_messages_workspace_id"), table_name="email_messages")
    op.drop_index("ix_email_messages_workspace_direction", table_name="email_messages")
    op.drop_index("ix_email_messages_thread_created", table_name="email_messages")
    op.drop_index(
        "ix_email_messages_provider_message",
        table_name="email_messages",
        postgresql_where=sa.text("provider_message_id IS NOT NULL"),
    )
    op.drop_table("email_messages")
    op.drop_index("ix_email_threads_workspace_status", table_name="email_threads")
    op.drop_index(op.f("ix_email_threads_workspace_id"), table_name="email_threads")
    op.drop_index(
        "ix_email_threads_provider_thread",
        table_name="email_threads",
        postgresql_where=sa.text("provider_thread_id IS NOT NULL"),
    )
    op.drop_index("ix_email_threads_last_activity", table_name="email_threads")
    op.drop_table("email_threads")
    # ### end Alembic commands ###
